$ErrorActionPreference = "Stop"

# --- Paths ---
$dev   = "lib/dev_quick_visit.dart"
$quick = "lib/features/visits/screens/quick_visit_screen.dart"

function Save([string]$p,[string]$s){ $s | Set-Content $p -Encoding UTF8 }
function GetRaw([string]$p){ if(!(Test-Path $p)){ throw "Missing $p" }; Get-Content $p -Raw }

# --- 1) Ensure dev entry that initializes Firebase with options + anonymous sign-in ---
$devContent = @'
import "package:flutter/material.dart";
import "package:firebase_core/firebase_core.dart";
import "package:firebase_auth/firebase_auth.dart";
import "firebase_options.dart"; // generated by flutterfire configure
import "features/visits/screens/quick_visit_screen.dart";

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await FirebaseAuth.instance.signInAnonymously();
  runApp(const _DevApp());
}

class _DevApp extends StatelessWidget {
  const _DevApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Quick Visit (DEV)",
      theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.teal),
      home: const QuickVisitScreen(),
    );
  }
}
'@
Save $dev $devContent

# --- 2) Inject user_id into Quick Visit payload (idempotent) ---
$src = GetRaw $quick

# add import if missing
if ($src -notmatch "(?m)^\s*import\s+['""]package:firebase_auth/firebase_auth\.dart['""];") {
  $src = $src -replace "(?s)(^import[^\n]*;\s*)", "`$1import 'package:firebase_auth/firebase_auth.dart';`r`n"
}

# add 'user_id' into the payload map if not present
if ($src -notmatch "['""]user_id['""]\s*:") {
  $src = [regex]::Replace(
    $src,
    "final\s+payload\s*=\s*<String,\s*dynamic>\s*\{\s*",
    "final payload = <String, dynamic>{`r`n                'user_id': FirebaseAuth.instance.currentUser?.uid,`r`n                ",
    1
  )
}

Save $quick $src

# --- 3) Optional: write Firestore rules + indexes (safe-ish dev defaults) ---
$rulesPath   = "firestore.rules"
$indexesPath = "firestore.indexes.json"

$rules = @'
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    // Public reads for dev to unblock pickers
    match /places/{id} {
      allow read: if true;
    }
    match /menu_items/{id} {
      allow read: if true;
    }

    // Visits: allow create for any signed-in user (anonymous OK)
    match /visits/{id} {
      allow create: if request.auth != null
        && request.resource.data.taste_rating is int
        && request.resource.data.portion_rating is int
        && request.resource.data.portion is map;
      allow read: if request.auth != null;
    }
  }
}
'@
$indexes = @'
{
  "indexes": [
    {
      "collectionGroup": "menu_items",
      "queryScope": "COLLECTION",
      "fields": [
        { "fieldPath": "place_id", "order": "ASCENDING" },
        { "fieldPath": "name",     "order": "ASCENDING" }
      ]
    }
  ],
  "fieldOverrides": []
}
'@

$rules | Set-Content $rulesPath -Encoding UTF8
$indexes | Set-Content $indexesPath -Encoding UTF8

Write-Host "`n> Formatting & fetching deps..."
flutter format $dev $quick | Out-Null
flutter pub get        | Out-Null

Write-Host "> You can now run the dev entry:"
Write-Host "flutter run -d windows -t lib/dev_quick_visit.dart" -ForegroundColor Cyan
Write-Host "`n> To deploy Firestore rules & indexes (requires firebase-tools):"
Write-Host "firebase deploy --only firestore:rules,firestore:indexes" -ForegroundColor Yellow
