name: similar_eats_desktop
description: Offline mock simulation of Similar Eats desktop
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.1.0
  collection: ^1.18.0
  firebase_core: ^4.1.0
  firebase_database: ^12.0.1
  firebase_remote_config: ^6.0.1
  firebase_auth: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/food1.jpg
    - assets/food2.jpg
    - assets/food3.jpg
    - assets/food4.jpg
