// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo2eHymkIWe87yZc6Vo_u8eeJoLgmr2bI',
    appId: '1:970307574487:web:354b49faa5b215780bee92',
    messagingSenderId: '970307574487',
    projectId: 'similar-eats',
    authDomain: 'similar-eats.firebaseapp.com',
    databaseURL: 'https://similar-eats-default-rtdb.firebaseio.com',
    storageBucket: 'similar-eats.firebasestorage.app',
    measurementId: 'G-PVB122JZ41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6dRUpYS5gtp-16sEjhbVYxmGLjlKVNok',
    appId: '1:970307574487:android:568d38b5042a6d3b0bee92',
    messagingSenderId: '970307574487',
    projectId: 'similar-eats',
    databaseURL: 'https://similar-eats-default-rtdb.firebaseio.com',
    storageBucket: 'similar-eats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8rPdr8hG0AJRcWItaGZ5lNY135cfUixI',
    appId: '1:970307574487:ios:0b7ee013a685a92a0bee92',
    messagingSenderId: '970307574487',
    projectId: 'similar-eats',
    databaseURL: 'https://similar-eats-default-rtdb.firebaseio.com',
    storageBucket: 'similar-eats.firebasestorage.app',
    iosBundleId: 'com.example.similarEatsDesktop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8rPdr8hG0AJRcWItaGZ5lNY135cfUixI',
    appId: '1:970307574487:ios:0b7ee013a685a92a0bee92',
    messagingSenderId: '970307574487',
    projectId: 'similar-eats',
    databaseURL: 'https://similar-eats-default-rtdb.firebaseio.com',
    storageBucket: 'similar-eats.firebasestorage.app',
    iosBundleId: 'com.example.similarEatsDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo2eHymkIWe87yZc6Vo_u8eeJoLgmr2bI',
    appId: '1:970307574487:web:256e1ce39a7c63820bee92',
    messagingSenderId: '970307574487',
    projectId: 'similar-eats',
    authDomain: 'similar-eats.firebaseapp.com',
    databaseURL: 'https://similar-eats-default-rtdb.firebaseio.com',
    storageBucket: 'similar-eats.firebasestorage.app',
    measurementId: 'G-V12WNG8Q73',
  );
}
