# ---- Similar Eats: Beta Prep Script ----
# Creates READMEs, RemoteConfig helper, Onboarding Quiz + Try List stubs.

param(
  [string]$Proj = "C:\projects\similar_eats_desktop"
)

$ErrorActionPreference = "Stop"

function Ensure-Dir($p) { if (-not (Test-Path $p)) { New-Item -ItemType Directory -Path $p | Out-Null } }

Write-Host "`n[Beta Prep] Using project: $Proj" -ForegroundColor Cyan

# 0) Verify firebase_options.dart exists (generated by flutterfire)
$firebaseOpts = Join-Path $Proj "lib\firebase_options.dart"
if (-not (Test-Path $firebaseOpts)) {
  Write-Host "WARNING: lib/firebase_options.dart not found. Run: flutterfire configure" -ForegroundColor Yellow
}

# 1) RemoteConfig helper (lib/shared/remote_config.dart)
$sharedDir = Join-Path $Proj "lib\shared"
Ensure-Dir $sharedDir
$remoteConfigPath = Join-Path $sharedDir "remote_config.dart"
@'
import 'package:firebase_remote_config/firebase_remote_config.dart';

class RemoteConfigService {
  RemoteConfigService._(this._rc);
  static RemoteConfigService? _instance;

  final FirebaseRemoteConfig _rc;

  static RemoteConfigService get instance {
    _instance ??= RemoteConfigService._(FirebaseRemoteConfig.instance);
    return _instance!;
  }

  Future<void> ensureReady() async {
    await _rc.setDefaults(const {
      "quick_eats_enabled": true,
      "quick_eats_min_quick_tags": 0,
      "quick_eats_late_cutoff_hour": 23,
    });
    await _rc.setConfigSettings(
      RemoteConfigSettings(
        fetchTimeout: Duration(seconds: 10),
        minimumFetchInterval: Duration(minutes: 15),
      ),
    );
    try {
      await _rc.fetchAndActivate();
    } catch (_) {
      // keep defaults on error
    }
  }

  bool getBool(String key, {required bool fallback}) {
    try { return _rc.getBool(key); } catch (_) { return fallback; }
  }

  int getInt(String key, {required int fallback}) {
    try { return _rc.getInt(key); } catch (_) { return fallback; }
  }
}
'@ | Set-Content -Path $remoteConfigPath -Encoding UTF8

# 2) READMEs (lightweight, handoff-friendly)
$readmes = @(
  @{ Path = Join-Path $Proj "README.md"; Content = @"
# Similar Eats – Root

**Purpose:** app entry, environment, global scripts.

## Quick Start
- `flutter pub get`
- `flutter run -d chrome`

## Environments
- Firebase project: `similar-eats`
- RTDB root: `/restaurants`

## Modules
- `lib/features/quick_eats`
- `lib/features/onboarding`
- `lib/features/try_list`
- `lib/shared`
"@ },
  @{ Path = Join-Path $Proj "lib\features\quick_eats\README.md"; Content = @"
# Quick Eats

**Purpose:** Toggle between **Quick** (fast service) and **Late Night** (open late).

## Data
- RTDB: `/restaurants/{id}`
  - `name: string`
  - `serviceTags: string[]`
  - `quickServiceFlag: bool`
  - `openLateFlag: bool`

## Remote Config
- `quick_eats_enabled: bool`
- `quick_eats_min_quick_tags: int`
- `quick_eats_late_cutoff_hour: int`

## UI
- `QuickEatsScreen` (toggle buttons)
- `RestaurantCard` (badges)
"@ },
  @{ Path = Join-Path $Proj "lib\features\onboarding\README.md"; Content = @"
# Onboarding

**Purpose:** quick taste quiz → saves preferences, improves rankings.

## Next
- Store quiz answers under `users/{uid}/prefs`
- RC gate for showing quiz at first run.
"@ },
  @{ Path = Join-Path $Proj "lib\features\try_list\README.md"; Content = @"
# Try List

**Purpose:** user can bookmark restaurants/dishes → retention + reminders.

## Data
- RTDB: `userTryList/{uid}/{restaurantId}: true`

## UI
- `TryListButton` to toggle; `TryListScreen` to review.
"@ }
)
foreach ($r in $readmes) {
  Ensure-Dir (Split-Path $r.Path)
  $r.Content | Set-Content -Path $r.Path -Encoding UTF8
}

# 3) Onboarding Taste Quiz (minimal working screen)
$onboardingDir = Join-Path $Proj "lib\features\onboarding\screens"
Ensure-Dir $onboardingDir
$onboardingScreen = Join-Path $onboardingDir "taste_quiz_screen.dart"
@'
import 'package:flutter/material.dart';

class TasteQuizScreen extends StatefulWidget {
  const TasteQuizScreen({super.key});
  @override
  State<TasteQuizScreen> createState() => _TasteQuizScreenState();
}

class _TasteQuizScreenState extends State<TasteQuizScreen> {
  final _answers = <String, bool>{'spicy': false, 'sweet': false, 'savory': true};

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Taste Quiz')),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          const Text('Pick what fits you (quick demo):'),
          const SizedBox(height: 12),
          ..._answers.keys.map((k) => SwitchListTile(
                title: Text(k[0].toUpperCase() + k.substring(1)),
                value: _answers[k] ?? false,
                onChanged: (v) => setState(() => _answers[k] = v),
              )),
          const SizedBox(height: 16),
          FilledButton(
            onPressed: () {
              // TODO: save under users/{uid}/prefs
              Navigator.pop(context);
            },
            child: const Text('Save & Continue'),
          ),
        ],
      ),
    );
  }
}
'@ | Set-Content -Path $onboardingScreen -Encoding UTF8

# 4) Try List (minimal repo + button + screen)
$tryDir = Join-Path $Proj "lib\features\try_list"
Ensure-Dir $tryDir
$tryRepoPath = Join-Path $tryDir "try_list_repo.dart"
@'
import 'package:firebase_database/firebase_database.dart';

class TryListRepo {
  TryListRepo({FirebaseDatabase? db}) : _db = db ?? FirebaseDatabase.instance;
  final FirebaseDatabase _db;

  Future<void> toggle(String uid, String restaurantId, bool add) async {
    final ref = _db.ref('userTryList/$uid/$restaurantId');
    if (add) {
      await ref.set(true);
    } else {
      await ref.remove();
    }
  }

  Future<Map<String, bool>> load(String uid) async {
    final snap = await _db.ref('userTryList/$uid').get();
    if (!snap.exists || snap.value is! Map) return {};
    final m = Map<String, dynamic>.from(snap.value as Map);
    return m.map((k, v) => MapEntry(k, v == true));
  }
}
'@ | Set-Content -Path $tryRepoPath -Encoding UTF8

$tryWidgetDir = Join-Path $Proj "lib\features\try_list\widgets"
Ensure-Dir $tryWidgetDir
$tryBtnPath = Join-Path $tryWidgetDir "try_list_button.dart"
@'
import 'package:flutter/material.dart';

class TryListButton extends StatelessWidget {
  const TryListButton({super.key, required this.inList, required this.onToggle});
  final bool inList;
  final VoidCallback onToggle;

  @override
  Widget build(BuildContext context) {
    return IconButton(
      tooltip: inList ? 'Remove from Try List' : 'Add to Try List',
      icon: Icon(inList ? Icons.bookmark : Icons.bookmark_outline),
      onPressed: onToggle,
    );
  }
}
'@ | Set-Content -Path $tryBtnPath -Encoding UTF8

$tryScreenDir = Join-Path $Proj "lib\features\try_list\screens"
Ensure-Dir $tryScreenDir
$tryScreenPath = Join-Path $tryScreenDir "try_list_screen.dart"
@'
import 'package:flutter/material.dart';

class TryListScreen extends StatelessWidget {
  const TryListScreen({super.key});

  @override
  Widget build(BuildContext context) {
    // TODO: Load actual try list; placeholder UI for now
    return Scaffold(
      appBar: AppBar(title: const Text('My Try List')),
      body: const Center(child: Text('Your saved places will appear here.')),
    );
  }
}
'@ | Set-Content -Path $tryScreenPath -Encoding UTF8

Write-Host "`nCreated/updated:" -ForegroundColor Green
Write-Host " - $remoteConfigPath"
Write-Host " - $($readmes[0].Path)"
Write-Host " - $($readmes[1].Path)"
Write-Host " - $($readmes[2].Path)"
Write-Host " - $($readmes[3].Path)"
Write-Host " - $onboardingScreen"
Write-Host " - $tryRepoPath"
Write-Host " - $tryBtnPath"
Write-Host " - $tryScreenPath"
Write-Host "`n[Beta Prep] Done.`n" -ForegroundColor Cyan
